version: '3'

services:
  nginx_proxy:
    build: .
    ports:
        - "80:80"
    links:
      - rabbit
      - vi_front
      - avatarapi
    depends_on:
      - rabbit
      - vi_front
      - avatarapi

  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment: 
      RABBITMQ_DEFAULT_PASS: assista
      RABBITMQ_DEFAULT_USER: assista

  vi_front:
    image: "vifront_vi_front"
    ports:
      - "4200"
    depends_on:
      - avatarapi
  
  avatarapi:
    image: assistagateway_virtual_interaction
    ports:
      - "3000"
    depends_on:
      - rabbit
    links:
      - rabbit
      
  bundles_server:
    image: assistabundleserver_bundles_server
    ports:
      - "8000"