version: '3'

services:
  nginx_proxy:
    build: .
    ports:
        - "8080:8080"
    links:
      - assista_gateway
      - rabbit
      - vi_front
    depends_on:
      - assista_gateway

  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment: 
      RABBITMQ_DEFAULT_PASS: assista
      RABBITMQ_DEFAULT_USER: assista

  vi_front:
    image: vi-front_vi_front
    ports:
      - "4200"
  
  assista_gateway:
    image: assista-gateway_assista_gateway 
    ports:
      - "3000"
    depends_on:
      - rabbit
    links:
      - rabbit
      - bundles_server
      
  bundles_server:
    image: bundle-server_bundles_server
    ports:
      - "8000"